name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Padronização de Código
        run: yarn lint

  unit:
    runs-on: ubuntu-latest
    needs: [inspection]

    steps:
      - uses: actions/checkout@v4

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Padronização de Código
        run: yarn run test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [unit]

    steps:
      - uses: actions/checkout@v4

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: subindo a aplicação
        run: yarn start & 

      - name: Testes E2E (end-to-end)
        run: yarn run e2e
        env:
          URL: 'http://localhost:3000/'

      - uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: ./playwright-report
